dependencies {
    minecraft libs.minecraft
    mappings loom.layered() {
        officialMojangMappings()
        parchment variantOf(libs.parchment) {
            artifactType('zip')
        }
    }
    modImplementation libs.fabricLoader
    modImplementation libs.fabricApi
    modImplementation "com.terraformersmc:modmenu:${modmenu_version}"

//    modImplementation(libs.balmFabric) {
//        changing = libs.versions.balm.get().contains("SNAPSHOT")
//    }
    testImplementation sourceSets.main.output
//    testImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    afterEvaluate {
        subprojects.each {
            implementation project(path: ":${it.path}", configuration: "namedElements")
            testImplementation project(":${it.path}").sourceSets.test.output
        }
    }
}