dependencies {
    minecraft libs.minecraft
    mappings loom.layered() {
        officialMojangMappings()
        parchment variantOf(libs.parchment) {
            artifactType('zip')
        }
    }
    modImplementation libs.fabricLoader
    modImplementation libs.fabricApi
    modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"

//    implementation("net.blay09.mods:balm-fabric:${balm_version}") {
//        changing = balm_version.contains('SNAPSHOT')
//    }
    testImplementation sourceSets.main.output
//    testImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    afterEvaluate {
        subprojects.each {
            implementation project(path: ":${it.path}", configuration: "namedElements")
            testImplementation project(":${it.path}").sourceSets.test.output
        }
    }
}