# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_id=dillonlib
mod_version=1.0
mod_name=DillonLib
description=Library for Dillon's mods.
mod_author=Dillon8775
credits=Dillon8775
license=All rights reserved unless explicitly stated.
logo=assets/dillonlib/icon
mc_version=mc1.21.1
supported_mc_versions=[1.21.1]
minecraft_version_range=[1.21.1, 1.21.2)
group=net.dillon.dillonlib

# Links
homepage=https://modrinth.com/mod/dillon-lib
sources=https://github.com/Dillon8775/Dillon-Lib
issues=https://github.com/Dillon8775/Dillon-Lib/issues
discord=https://discord.gg/vfqEAn4YFy

# Common
java_version=21
minecraft_version=1.21.1

# Balm version
# balm_version=26.1.0.6

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=
fabric_loader_version=
modmenu_version=11.0.4

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=
neoforge_loader_version_range=[4,)

# Other (not required in multiloader-common.gradle)
curseforge_project_id=1275791
modrinth_project_id=Sj7HGYie
changelog_file=current_changelog.md

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false