import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    alias libs.plugins.modDevGradle
    alias libs.plugins.curseForgeGradle
    alias libs.plugins.modrinthMinotaur
}

apply from: rootProject.file('repositories.gradle')
apply from: 'dependencies.gradle'

neoForge {
    version = libs.neoForge.get().version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':neoforge').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment.parchmentArtifact = libs.parchment.get().toString()

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }

        client {
            client()
        }
//        test {
//            client()
//        }
        data {
            clientData()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
//        "quesoinstance" {
//            sourceSet sourceSets.test
//        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

//sourceSets {
//    test {
//        compileClasspath += sourceSets.main.output
//        runtimeClasspath += sourceSets.main.output
//    }
//}
//
tasks.named('test') {
    enabled = false
}

tasks.register('curseforge', TaskPublishCurseForge) {
    dependsOn('build')
    description = 'Publishes the NeoForge build to CurseForge.'
    group = 'publishing'

    apiToken = project.findProperty("curseforge.api_key") ?: System.getenv("CURSEFORGE_TOKEN") ?: "none"

    def projectId = findProperty("curseforge_project_id")
    onlyIf {
        projectId != null
    }
    if (projectId) {
        def mainFile = upload(findProperty("curseforge_project_id"), jar.archiveFile.get().asFile)
        mainFile.displayName = "[${mc_version.substring(2)}] $mod_name ${mod_version}"
        mainFile.changelog = rootProject.file("${changelog_file}").text
        // mainFile.addRequirement("balm")
        mainFile.addGameVersion(libs.minecraft.get().version)
        mainFile.releaseType = "release"
        project.findProperty("curseforge_environments")?.split(",")?.toList()?.each { mainFile.addEnvironment(it) }
        mainFile.addModLoader("NeoForge")
        mainFile.addEnvironment("Client")
        mainFile.addEnvironment("Server")
    }
}

modrinth {
    token = project.findProperty("modrinth.token") ?: System.getenv("MODRINTH_TOKEN") ?: "none"
    projectId = findProperty("modrinth_project_id")
    versionType = "release"

    versionNumber = project.mod_version.toString()
    versionName = "[mc${libs.minecraft.get().version}] ${mod_name} ${project.mod_version}"

    uploadFile = jar
    def changelogFile = rootProject.file("${changelog_file}")
    if (changelogFile.exists()) {
        changelog = changelogFile.text
    }
    gameVersions = [libs.minecraft.get().version]
    loaders = ['neoforge']
    dependencies {
        // required.project "balm"
    }
    additionalFiles = files(
            tasks.named("sourcesJar"),
            tasks.named("javadocJar")
    )
}

def neoForgeSnapshotUrl = findProperty("neoforge_snapshot_url")
if (neoForgeSnapshotUrl != null && !neoForgeSnapshotUrl.isBlank()) {
    repositories {
        maven {
            name = 'Maven for NeoForge Snapshots'
            url = neoForgeSnapshotUrl
            content {
                includeModule('net.neoforged', 'neoforge')
                includeModule('net.neoforged', 'testframework')
            }
        }
    }
}